FROM python:3.10-alpine
WORKDIR /app

RUN apk update
RUN apk upgrade --no-cache
RUN apk add curl

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 3000

ENTRYPOINT flask run --port=3000 --host=0.0.0.0 --debug --reload
