FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

COPY ServiceDiscovery.csproj .
RUN dotnet restore ServiceDiscovery.csproj
COPY . .

ENTRYPOINT ["dotnet", "run", "--config", "Release", "--no-restore", "--project", "ServiceDiscovery.csproj"]
